name: Foodlitzer

configs:
  Debug: debug
  Release: release

settings:
  DEVELOPMENT_TEAM: H7BM7N56V5
  CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: true

options:
  bundleIdPrefix: dev.vcoutasso

targets:
  Foodlitzer:
    type: application
    platform: iOS
    deploymentTarget: 15.0
    settings:
      TARGETED_DEVICE_FAMILY: 1
      INFOPLIST_FILE: Foodlitzer/Supporting-Files/Info.plist
    sources: Foodlitzer
    preBuildScripts:
      - name: SwiftLint
        script: |
          "${PODS_ROOT}/SwiftLint/swiftlint" --config ../config/swiftlint.yml
      - name: SwiftGen
        script: |
          "${PODS_ROOT}/SwiftGen/bin/swiftgen" config run --config ../config/swiftgen.yml

  FoodlitzerTests:
    type: bundle.unit-test
    platform: iOS
    settings:
      FRAMEWORK_SEARCH_PATHS: "$(inherited)"
      HEADER_SEARCH_PATHS: "${SRCROOT}/Pods/Firebase/CoreOnly/Sources"
    sources: FoodlitzerTests
    dependencies:
      - target: Foodlitzer

schemes:
  Foodlitzer:
    build:
      targets:
        Foodlitzer: all
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - name: FoodlitzerTests
          randomExecutionOrder: true
