name: SpiderVerse

configs:
  Debug: debug
  Release: release

settings:
  DEVELOPMENT_TEAM: H7BM7N56V5
  CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: true

options:
  bundleIdPrefix: com.vcoutasso

targets:
  SpiderVerse:
    type: application
    platform: iOS
    deploymentTarget: 14.0
    settings:
      TARGETED_DEVICE_FAMILY: 1
    sources: SpiderVerse
    preBuildScripts:
      - name: SwiftLint
        script: |
          "${PODS_ROOT}/SwiftLint/swiftlint" --config ../config/swiftlint.yml
      - name: SwiftGen
        script: |
          "${PODS_ROOT}/SwiftGen/bin/swiftgen" config run --config ../config/swiftgen.yml

  SpiderVerseTests:
    type: bundle.unit-test
    platform: iOS
    sources: SpiderVerseTests
    dependencies:
      - target: SpiderVerse

schemes:
  SpiderVerse:
    build:
      config: Debug
      targets:
        SpiderVerse: all
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - name: SpiderVerseTests
          randomExecutionOrder: true
